# Generated by Django 4.2.23 on 2025-07-15 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('gamer_first_name', models.CharField(max_length=100, null=True)),
                ('gamer_last_name', models.CharField(max_length=100, null=True)),
                ('guardian_first_name', models.CharField(max_length=100, null=True)),
                ('guardian_last_name', models.CharField(max_length=100, null=True)),
                ('custody_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('married_parent', 'Biological parent, married'), ('divorced_parent', 'Biological parent, divorced with custody order'), ('adoptive_parent', 'Adoptive parent(s)'), ('legal_guardian', 'Legal Guardian with custody order'), ('no_custody', 'Do not have legal custody'), ('other', 'Other')], max_length=30), blank=True, default=list, size=None, verbose_name='Do you have legal custody of the gamer (if gamer is a minor)')),
                ('custody_other_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.TextField(max_length=200, null=True)),
                ('roblox_gamertag', models.CharField(blank=True, max_length=100, null=True)),
                ('discord_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('xbox_gamertag', models.CharField(blank=True, max_length=100, null=True)),
                ('ps_gamertag', models.CharField(blank=True, max_length=100, null=True)),
                ('description_predators', models.TextField(max_length=200, null=True)),
                ('description_medical_psychological', models.TextField(max_length=200, null=True)),
                ('description_economic_loss', models.TextField(max_length=200, null=True)),
                ('first_contact', models.DateField(blank=True, null=True)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('complained_to_roblox', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('emails_to_roblox', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('complained_to_apple', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('emails_to_apple', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('complained_to_cc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('emails_to_cc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('cc_names', models.TextField(max_length=200, null=True)),
                ('contacted_police', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('emails_to_police', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('police_details', models.TextField(max_length=200, null=True)),
                ('other_complaints', models.TextField(max_length=200, null=True)),
                ('asked_for_photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('minor_sent_photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30), blank=True, default=list, size=None)),
                ('predator_distributed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=30), blank=True, default=list, size=None)),
                ('predator_threatened', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=30), blank=True, default=list, size=None)),
                ('in_person_meeting', models.TextField(max_length=200, null=True)),
                ('additional_info', models.TextField(max_length=200, null=True)),
                ('discovery_info', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intake_form',
            },
        ),
    ]
