# Generated by Django 4.2.23 on 2025-07-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0003_question_option_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='additional_notes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
