# Generated by Django 4.2.23 on 2025-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0004_userdetail_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
