# Generated by Django 4.2.23 on 2025-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0005_alter_userdetail_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
