# Generated by Django 4.2.23 on 2025-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0007_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='redirect_to_retainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='requires_parental_signature',
            field=models.BooleanField(default=False),
        ),
    ]
