# Generated by Django 4.2.23 on 2025-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0008_option_is_eligible_option_redirect_to_retainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rejected', 'Rejected (>20 years)'), ('eligible_no_parent', 'Eligible (18-20, no parent signature)'), ('eligible_with_parent', 'Eligible (<=17, parent signature required)')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
