# Generated by Django 4.2.23 on 2025-07-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0009_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roblex_app.emailtemplate'),
        ),
    ]
