# Generated by Django 4.2.23 on 2025-08-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0010_emaillog_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docuseal_submission_id', models.IntegerField(unique=True)),
                ('docuseal_submitter_id', models.IntegerField()),
                ('docuseal_slug', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Signer'), ('opened', 'Opened by Signer'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('signed_document_url', models.URLField(blank=True, null=True)),
                ('audit_log_url', models.URLField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('retainer_minor', 'Retainer Agreement - Minor (with parent signature)'), ('retainer_adult', 'Retainer Agreement - Adult (18-20)'), ('intake_supplemental', 'Supplemental Intake Document')], max_length=50, unique=True)),
                ('docuseal_template_id', models.IntegerField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('form.viewed', 'Form Viewed'), ('form.started', 'Form Started'), ('form.completed', 'Form Completed'), ('form.declined', 'Form Declined'), ('submission.created', 'Submission Created'), ('submission.completed', 'Submission Completed'), ('submission.expired', 'Submission Expired')], max_length=30)),
                ('webhook_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='roblex_app.documentsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='document_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roblex_app.documenttemplate'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='intake_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roblex_app.intakeform'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='user_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to='roblex_app.userdetail'),
        ),
    ]
