# Generated by Django 4.2.23 on 2025-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0010_emaillog_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('requires_parental_signature', models.BooleanField(default=False)),
                ('redirect_to_retainer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['min_age'],
            },
        ),
        migrations.AddField(
            model_name='userdetail',
            name='gamer_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
