# Generated by Django 4.2.23 on 2025-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0012_add_userdetail_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Signer'), ('opened', 'Opened by Signer'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
