# Generated by Django 4.2.23 on 2025-08-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0013_update_document_submission_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubmission',
            name='audit_log_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='signed_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
