# Generated by Django 4.2.23 on 2025-08-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0014_alter_documentsubmission_audit_log_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='gamer_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
