# Generated by Django 4.2.23 on 2025-08-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0015_userdetail_gamer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(choices=[('retainer_minor', 'Retainer Agreement - Minor (with parent signature)'), ('retainer_adult', 'Retainer Agreement - Adult (18-20)'), ('intake_supplemental', 'Supplemental Intake Document'), ('florida_disclosure', 'Florida Disclosure Document (Zipcode 32003-34997)')], max_length=50, unique=True),
        ),
    ]
