# Generated by Django 4.2.23 on 2025-08-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0016_add_florida_disclosure_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='user_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='roblex_app.userdetail'),
        ),
    ]
