# Generated by Django 4.2.23 on 2025-08-07 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roblex_app', '0017_intakeform_user_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the law firm', max_length=200)),
                ('subdomain', models.CharField(help_text="Subdomain identifier (e.g., 'hilliard' for hilliard.roblox.nextkeylitigation.com)", max_length=100, unique=True)),
                ('contact_email', models.EmailField(help_text='Primary contact email for the law firm', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Law firm address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this law firm is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law Firm',
                'verbose_name_plural': 'Law Firms',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='userdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.CreateModel(
            name='LawFirmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('law_firm_admin', 'Law Firm Administrator'), ('law_firm_staff', 'Law Firm Staff'), ('law_firm_viewer', 'Read Only Access')], default='law_firm_staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('law_firm', models.ForeignKey(blank=True, help_text='Leave blank for super administrators', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='roblex_app.lawfirm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='law_firm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Law Firm User',
                'verbose_name_plural': 'Law Firm Users',
            },
        ),
        migrations.AddField(
            model_name='intakeform',
            name='law_firm',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from user_detail.law_firm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='roblex_app.lawfirm'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='law_firm',
            field=models.ForeignKey(blank=True, help_text='Law firm this lead belongs to (auto-assigned based on subdomain)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='roblex_app.lawfirm'),
        ),
    ]
