# Generated by Django 4.2.23 on 2025-08-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0018_lawfirm_alter_userdetail_options_lawfirmuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='law_firm',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global templates, set for law firm-specific overrides', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='roblex_app.lawfirm'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(choices=[('retainer_minor', 'Retainer Agreement - Minor (with parent signature)'), ('retainer_adult', 'Retainer Agreement - Adult (18-20)'), ('intake_supplemental', 'Supplemental Intake Document'), ('florida_disclosure', 'Florida Disclosure Document (Zipcode 32003-34997)')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('name', 'law_firm')},
        ),
    ]
