# Generated by Django 4.2.23 on 2025-08-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0019_add_law_firm_to_document_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsubmission',
            old_name='docuseal_slug',
            new_name='nextkeysign_slug',
        ),
        migrations.RenameField(
            model_name='documentsubmission',
            old_name='docuseal_submission_id',
            new_name='nextkeysign_submission_id',
        ),
        migrations.RenameField(
            model_name='documentsubmission',
            old_name='docuseal_submitter_id',
            new_name='nextkeysign_submitter_id',
        ),
        migrations.RenameField(
            model_name='documenttemplate',
            old_name='docuseal_template_id',
            new_name='nextkeysign_template_id',
        ),
    ]
