# Generated by Django 4.2.23 on 2025-08-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0019_add_law_firm_to_document_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='agreement_status',
            field=models.CharField(blank=True, choices=[('agree', 'I Agree'), ('not_agree', 'I Do Not Agree')], max_length=20, null=True),
        ),
    ]
