# Generated by Django 4.2.23 on 2025-08-18 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roblex_app', '0021_userdetail_agreement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person submitting the form', max_length=200)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (only for Parents Page)', max_length=20)),
                ('state_location', models.CharField(blank=True, help_text='State/Location (only for Parents Page)', max_length=100)),
                ('description', models.TextField(help_text='Description of concern or issue')),
                ('lead_source', models.CharField(choices=[('parents', 'Parents Page'), ('kids', 'Kids Page')], help_text='Which landing page the lead came from', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted to Intake'), ('declined', 'Declined'), ('inactive', 'Inactive')], default='new', help_text='Current status of this lead', max_length=15)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('referrer', models.URLField(blank=True, help_text='Referring page URL', max_length=500)),
                ('contacted_at', models.DateTimeField(blank=True, help_text='When the lead was first contacted', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to follow up with this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('law_firm', models.ForeignKey(blank=True, help_text='Law firm this lead belongs to (auto-assigned based on subdomain)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_page_leads', to='roblex_app.lawfirm')),
            ],
            options={
                'verbose_name': 'Landing Page Lead',
                'verbose_name_plural': 'Landing Page Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageLeadEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(help_text="Type of email (e.g., 'new_lead_notification', 'auto_reply')", max_length=50)),
                ('recipient_email', models.EmailField(help_text='Email address where notification was sent', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='roblex_app.landingpagelead')),
            ],
            options={
                'verbose_name': 'Landing Page Lead Email',
                'verbose_name_plural': 'Landing Page Lead Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='landingpagelead',
            index=models.Index(fields=['law_firm', 'status'], name='roblex_app__law_fir_605927_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpagelead',
            index=models.Index(fields=['lead_source', 'created_at'], name='roblex_app__lead_so_78e366_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpagelead',
            index=models.Index(fields=['email'], name='roblex_app__email_eb5a61_idx'),
        ),
    ]
