# Generated by Django 4.2.23 on 2025-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0022_landingpagelead_landingpageleademail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagelead',
            name='description',
            field=models.TextField(blank=True, help_text='Description of concern or issue (optional)'),
        ),
    ]
