# Generated by Django 4.2.23 on 2025-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0024_update_email_template_dynamic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='gamer_dob',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='working_with_attorney',
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='subdomain',
            field=models.CharField(help_text="Subdomain identifier (e.g., 'hilliard' for hilliard.nextkeylitigation.com)", max_length=100, unique=True),
        ),
    ]
