# Generated by Django 4.2.23 on 2025-08-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0025_remove_userdetail_gamer_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='available_slots',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
