# Generated by Django 4.2.23 on 2025-08-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roblex_app', '0026_intakeform_available_slots'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question', 'selected_option')},
        ),
    ]
