services:
  web:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
