services:
  web:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./generate-ssl.sh:/generate-ssl.sh
      - static_volume:/app/static
      - ssl_certs:/etc/nginx/ssl
    depends_on:
      - web
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    command: >
      sh -c "apk add --no-cache openssl &&
             sh /generate-ssl.sh &&
             nginx -g 'daemon off;'"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  ssl_certs:
