version: '3.8'

services:
  web:
    build: .
    expose:
      - "8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: roblox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
