services:
  web:
    command: >
      sh -c "python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy port

  # For local development, expose fb-landing-page directly
  fb-landing-page:
    ports:
      - "3001:80"  # Access React app directly at localhost:3001
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  static_volume:
