# Generated by Django 4.2.23 on 2025-08-10 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docuseal_submission_id', models.CharField(blank=True, max_length=100)),
                ('docuseal_submitter_id', models.CharField(blank=True, max_length=100)),
                ('docuseal_slug', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('signed_document_url', models.URLField(blank=True)),
                ('audit_log_url', models.URLField(blank=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Submission',
                'verbose_name_plural': 'Document Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('retainer_agreement', 'Retainer Agreement'), ('engagement_letter', 'Engagement Letter'), ('fee_agreement', 'Fee Agreement'), ('disclosure_form', 'Disclosure Form'), ('authorization_form', 'Authorization Form')], max_length=50)),
                ('docuseal_template_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('retainer_invitation', 'Retainer Document Invitation'), ('reminder_email', 'Document Reminder'), ('completion_confirmation', 'Document Completion')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Supported placeholders: [First Name Injured], [Last Name Injured], [Name], [State], [Age]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='retainer_excel_uploads/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_rows', models.IntegerField(blank=True, null=True)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_submissions', models.IntegerField(default=0)),
                ('failed_submissions', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retainer_app.documenttemplate')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retainer_app.emailtemplate')),
            ],
            options={
                'verbose_name': 'Excel Upload',
                'verbose_name_plural': 'Excel Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law Firm',
                'verbose_name_plural': 'Law Firms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetainerRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('first_name_injured', models.CharField(blank=True, max_length=100)),
                ('last_name_injured', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to DocuSeal'), ('completed', 'Document Completed'), ('failed', 'Failed'), ('skipped', 'Skipped (Invalid Data)')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('excel_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='retainer_app.excelupload')),
            ],
            options={
                'verbose_name': 'Retainer Recipient',
                'verbose_name_plural': 'Retainer Recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawFirmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('law_firm_admin', 'Law Firm Administrator'), ('law_firm_staff', 'Law Firm Staff'), ('law_firm_viewer', 'Read Only Access')], default='law_firm_staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('law_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='retainer_app.lawfirm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retainer_law_firm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Law Firm User',
                'verbose_name_plural': 'Law Firm Users',
            },
        ),
        migrations.AddField(
            model_name='excelupload',
            name='law_firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to='retainer_app.lawfirm'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='law_firm',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='retainer_app.lawfirm'),
        ),
        migrations.CreateModel(
            name='DocumentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('webhook_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='retainer_app.documentsubmission')),
            ],
            options={
                'verbose_name': 'Document Webhook Event',
                'verbose_name_plural': 'Document Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='law_firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='retainer_app.lawfirm'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='document_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retainer_app.documenttemplate'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_submission', to='retainer_app.retainerrecipient'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('name', 'law_firm')},
        ),
    ]
