# Generated by Django 4.2.23 on 2025-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retainer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubmission',
            name='audit_log_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='signed_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
