# Generated by Django 4.2.23 on 2025-08-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retainer_app', '0002_alter_documentsubmission_audit_log_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='display_name',
            field=models.CharField(default=0, help_text='Display name for this retainer type', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(default=0, help_text='Template type (invitation, reminder, completion, etc.)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this retainer agreement and what cases it covers'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(help_text="Custom retainer type name (e.g., 'Kratom Retainer', 'Realpage Retainer', etc.)", max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Supported placeholders: [First Name Injured], [Last Name Injured], [Name], [State], [Age], [External ID]'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text="Email template name (e.g., 'Kratom Invitation', 'Realpage Reminder', etc.)", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('name', 'law_firm')},
        ),
    ]
