# Generated by Django 4.2.23 on 2025-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retainer_app', '0003_documenttemplate_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='email_from_email',
            field=models.EmailField(blank=True, help_text='From email address (defaults to contact_email)', max_length=254),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='email_from_name',
            field=models.CharField(blank=True, help_text='Display name for outgoing emails', max_length=255),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password/app password', max_length=255),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP username/email', max_length=255),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP server port'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL encryption'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption'),
        ),
    ]
