# Generated by Django 4.2.23 on 2025-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retainer_app', '0004_lawfirm_email_from_email_lawfirm_email_from_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirm',
            name='email_from_email',
            field=models.EmailField(blank=True, help_text='From email address for notifications', max_length=254),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='email_from_name',
            field=models.CharField(blank=True, help_text='From name for notifications', max_length=255),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password or app password (encrypted)', max_length=500),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)'),
        ),
    ]
