# Generated by Django 4.2.23 on 2025-08-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retainer_app', '0005_alter_lawfirm_email_from_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsubmission',
            old_name='docuseal_slug',
            new_name='nextkeysign_slug',
        ),
        migrations.RenameField(
            model_name='documentsubmission',
            old_name='docuseal_submission_id',
            new_name='nextkeysign_submission_id',
        ),
        migrations.RenameField(
            model_name='documentsubmission',
            old_name='docuseal_submitter_id',
            new_name='nextkeysign_submitter_id',
        ),
        migrations.RenameField(
            model_name='documenttemplate',
            old_name='docuseal_template_id',
            new_name='nextkeysign_template_id',
        ),
        migrations.AlterField(
            model_name='retainerrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to NextKeySign'), ('completed', 'Document Completed'), ('failed', 'Failed'), ('skipped', 'Skipped (Invalid Data)')], default='pending', max_length=20),
        ),
    ]
