# Generated by Django 4.2.23 on 2025-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retainer_app', '0006_rename_docuseal_slug_documentsubmission_nextkeysign_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 Dashboard',
                'verbose_name_plural': '📊 Dashboard',
                'managed': False,
            },
        ),
    ]
